### ISSUE TITLE
"data": [] is all that is returned

### ISSUE THREAD

**Issue by anton-dealmeida** [toniton/sails-datatables#1]
Hi there,

I have installed your npm package (I'm using SailsJS v0.12) and when I implement the ajax call or try to make a call to /api/user/datatable all I get back from the call is this:
`{
  "draw": 0,
  "recordsTotal": 5,
  "recordsFiltered": 0,
  "iTotalRecords": 5,
  "iTotalDisplayRecords": 0,
  "data": []
}`

That tells me it does see the 5 records in my database but it doesn't return the actual dataset itself.

How would you implement the use of this datatable with jQueryUI's DataTables?

**Comment by toniton** [comment]
@anton-dealmeida I think the request you are sending is empty. Please use a post method and ensure that the datatables parameters are properly set. Can you send me a sample of your request please?

**Comment by anton-dealmeida** [comment]
@toniton So the request I send looks as follow, (I might be messing it up I'm still kind of a junior trying to swim about in a world of JavaScript)

```
ajax: {
   url: '/api/v1/permissions/datatable',
   type: 'GET',
}
```

Theoretically that should just return everything if I post to it. It does return something but the data object in the returned json is empty...

If we could get this to work correctly with either an ajax or websocket call it'll save me a lot of headaches with pagination...

**Comment by toniton** [comment]
@anton-dealmeida Please can you send me the response you get, I'm guessing you need to set 
```
ajax: {
   url: '/api/v1/permissions/datatable',
   type: 'GET',
   dataSrc: '...'
}
```
dataSrc attribute. Please respond, this issues would be closed and marked solved in 24hrs
